language: node_js
node_js:
  - "12.13"

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn run build

script:
  - docker build -t xlor-judge .
  - docker run --name=judge -d --privileged -p 3000:3000 xlor-judge /bin/bash "./run.sh"