language: node_js

services:
  - docker

before_install:
  - docker build -t xlor-judge .
  - docker run --name=judge -d --privileged -p 3000:3000 xlor-judge /bin/bash "./run.sh"

script:
  - curl http://localhost:3000/ping