language: node_js
node_js:
  - "12"

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn run build

script:
  - yarn run test
  - docker build -t xlor-judge .
  - docker run --name=judge -d --privileged -p 3000:3000 xlor-judge
  - docker build -t test-judge -f scripts/testdocker/Dockerfile .
  - docker run -rm test-judge
