language: node_js
node_js:
  - "12"

services:
  - docker

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn run build
  - yarn run test

script:
  - docker build -t xlor-judge .
  - docker run --name=judge -d --privileged -p 3000:3000 xlor-judge