language: node_js
node_js:
  - "12"

services:
  - docker
  - redis-server

env:
  - DEFAULT_REDIS=true

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - useradd -r compiler

install:
  - yarn
  - yarn run build

script:
  - yarn run test
  - docker build -t xlor-judge .
  - docker run --name=judge -d --privileged -p 3000:3000 xlor-judge
