version: '2.1'

services:
  judge:
    container_name: judge
    image: xlor-judge
    build:
      context: .
    privileged: true
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ENABLE_POLYGON=true
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./data:/judge/run/data
  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
