version: '2.1'

services:
  judge:
    container_name: judge
    image: xlor-judge
    build:
      context: .
      args:
        port: 3000
        mode: production
    privileged: true
    ports:
      - 3000:3000
    depends_on:
      - redis
    links:
      - redis
  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
