name: Docker Image CI

on:
  push:
    branches:
      - master
      - nest
  schedule:
    - cron: "0 0 * * 1"

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build . --file test/Dockerfile --tag judge-test:$(date +%s)
    - name: Run Docker image
      run: docker run judge-test --privileged -v ./data:/judge/run/data
