name: Docker Image CI

on:
  push:
    branches:
      - master
      - nest
      - fastify
  schedule:
    - cron: "0 0 * * 1"

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Test Docker image
      run: docker-compose --file docker-compose.test.yml up
