name: Node CI

on:
  push:
    branches:
      - master
      - nest
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
